version: '3'

services:
  mongo:
    image: mongo
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
     - bad-bank

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
     - bad-bank

  redis:
    image: redis
    networks:
     - bad-bank

  api:
    image: node:alpine
    ports:
      - 4000:4000
    command: yarn dev
    working_dir: /app
    env_file: .env
    volumes:
      - $PWD:/app
    depends_on:
      - mongo
      - redis
    networks:
     - bad-bank

networks:
  bad-bank:
    name: 'bad-bank'