version: '3'

services:
  web:
    image: node:alpine
    ports:
      - 3000:3000
    command: yarn dev
    working_dir: /app
    env_file:
      - .env
    volumes:
      - $PWD:/app
    networks:
     - bad-bank

networks:
  bad-bank:
    name: 'bad-bank'
    external: true
